### ISSUE TITLE
Pascal code to do any interactions

### ISSUE THREAD

**Issue by RakeshShresthaNP** [castle-engine/bad-chess#1]
In article you mentioned .. We have designed a 3D application using Castle Game Engine with a bit of physics.
We didn’t yet write any Pascal code to do any interactions — this will be done in the
next part of the article.

Have you started it or do you have any guidelines to do so may be I am willing to add pgn parser and pgn play command to make it further useful.

**Comment by michaliskambi** [comment]
The 2nd part of the article is coming next week. I didn't do it yet, but I did promise to do it for next week, so it shall be done :) I'll keep this issue open until then.

In the meantime, you can follow https://castle-engine.io/physics and https://castle-engine.io/viewport_and_scenes_from_code for various links how to use code to modify 3D scene using physics. And see `examples/physics/` in CGE.

Note that I don't really want to extend the example *for the article* with PGN parser, just to keep the article simpler. But naturally this would be a great thing to turn this more into "proper" chess game. If you want to go in this direction, you're of course welcome and I would be very happy to link to your code (and/or merge it into this repo as another project version, I guess "proper chess") -- as a direction how to make a proper chess game using CGE.

**Comment by michaliskambi** [comment]
The 2nd part is done, and available in this repo now! :)

Read it here: https://github.com/castle-engine/bad-chess/blob/master/article/castle_game_engine_bad_chess_2.adoc .

You can also just play the resulting "game" by downloading it from here: https://castle-engine.itch.io/bad-chess . Ready binaries for Windows and Linux.

The `project` subdirectory of this repo ( https://github.com/castle-engine/bad-chess/tree/master/project ) now also contains 2nd project, the end result of the 2nd part of the article.

Enjoy!
